### PR TITLE
readded the Q1 portfolio to keep it sync

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by genbien — DISMISSED** [review]
Will we need to update this every quarter?

**Comment by ghost** [comment]
@genbien Yes that's how it works for now, we only have to do this once a quarter though !

**Comment by anaselmhamdi** [comment]
In this batch of commits, I changed the sync view to be able to take milestone names as a parameter. 
I also changed the terraform file to create a trigger for Q1 2022 and Q2 2022.

**Review by ascavalcante — COMMENTED** [review]
lgtm

**Review by FelixEnescu — APPROVED** [review]

**Pull request merged**
